### ISSUE TITLE
Tiled and Node.js

### ISSUE THREAD

**Issue by marcinj1** [RSamaium/CanvasEngine#10]
Hi !
How to use Tiled in Node.js server. I mean sending map object to client.

**Comment by RSamaium** [comment]
Hello,

Indeed, the class Tiled mixture data loading and display. I look to rectify it.

**Comment by RSamaium** [comment]
Added in 1.3.0 :

https://github.com/RSamaium/CanvasEngine/tree/master/examples/tiled_server
