### ISSUE TITLE
Resizing canvas

### ISSUE THREAD

**Issue by morgash1989** [RSamaium/CanvasEngine#11]
It is planned to add a resize functionnality to the scene, to be able to control the size of the canvas, when the browser is resized for exemple ? Or to manage the size of different devices ?

**Comment by RSamaium** [comment]
Hello,

Yes, it is to be considered for future releases

**Comment by RSamaium** [comment]
Hello,

You can resize the canvas in version 1.2.6

http://canvasengine.net/doc/?p=core.canvas.setSize
