### ISSUE TITLE
Class inheritance

### ISSUE THREAD

**Issue by maxailloud** [RSamaium/CanvasEngine#12]
I just saw your performance test for CanvasEngine classes (http://jsperf.com/native-class-and-canvasengine-class and http://jsperf.com/native-class-and-canvasengine-class-test2).

Before thinking about using this method for creating class I wanted to know if there's a way to make inheritance with this method?

**Comment by RSamaium** [comment]
Hello,

Yes, you can to make inheritance with `extend` method

```
Class.create("Bar", {


});

Class.create("Foo", {

   mymethod: function() {

    }

 }).extend("Bar");
```

http://canvasengine.net/doc/?p=core.class.extend

**Comment by maxailloud** [comment]
Ok I found the extend method but I don't know why I tought it was not for inheritance.

Thanks.
