### ISSUE TITLE
Can't load isometric map

### ISSUE THREAD

**Issue by TheKassaK** [RSamaium/CanvasEngine#14]
Hi !

I have make an isometric map with Tiled, i export into a json file, and i try to use it with your canvasengine.

What i need to do for draw an isometric map ? For now, when i try to draw my map with this isometric json, i have a map like : 

![sans titre](https://f.cloud.github.com/assets/4355752/466705/8966fef0-b662-11e2-9712-657e9137132a.png)

Do you have any ideas ? Thanks :)

**Comment by RSamaium** [comment]
Hello,

Currently, CanvasEngine does not support isometric with Tiled.

**Comment by TheKassaK** [comment]
Ok .. ^^

I really need that, can you help me if i develop this function ? Where i can begin ? What i need to change ?

After that, i give you the new code :)

**Comment by RSamaium** [comment]
I have very little time to work on isometric but if you want to try, the file is `extends/Tiled.js`

**Comment by Vadorequest** [comment]
Any improvements?
I want to use isometric too, and I'm not alone :p
