### ISSUE TITLE
Mouseover and Mousemove fire when mouse stops

### ISSUE THREAD

**Issue by mbabuskov** [RSamaium/CanvasEngine#15]
Hi, I'm evaluating CanvasEngine for a web-browser game I'm about to make. I want to have some effect when mouse hovers over sprites. I'm using code like this:

```
    this.playbtn.on("mouseover", function(e) {
        this.opacity = 0.5;
    });
    this.playbtn.on("mouseout", function(e) {
        this.opacity = 1;
    });
```

The problem is that opacity does not change until mouse stops. If I hover the mouse over a picture and keep moving it around the event never fires. If I move away from the picture and then stop moving the mouse, the event fires (which is too late, and also wrong IMHO).

I'm using CanvasEngine stable 86b3eb7 on Firefox 20.0 32-bit on Linux.

**Comment by RSamaium** [comment]
Hello,

Did you give a size to the element ?

[http://jsfiddle.net/WebCreative5/Y9Kum/](http://jsfiddle.net/WebCreative5/Y9Kum/)

**Comment by mbabuskov** [comment]
Yes.

I see the same problem in the jsFiddle you gave. As long as the mouse moves, event does not fire. Note that it does not happen always consistently, and if you leave the element and get back in, it fires right away. I'm not sure why is this. Using a larger (400x400) box makes it much easier to reproduce.

**Comment by RSamaium** [comment]
Very strange, I just tested on Firefox 20 and it works well. Hmm...

**Comment by mbabuskov** [comment]
I'll try to create a video today if I find some time. I also tried EaselJS, and there it works properly.
