### ISSUE TITLE
Multiplayer with node.js 0.10.xx seems not to work

### ISSUE THREAD

**Issue by Yutenko** [RSamaium/CanvasEngine#16]
Hey,

i'Ve postet my problem with canvasengine also on http://stackoverflow.com/questions/17253722/canvasengine-and-node-js-10-x

Maybe one of you guys can help me out?

Many thanks for this great engine

**Comment by RSamaium** [comment]
Model changed in 1.3.0 and tested with Node.js 0.10.5.

If you still have problems, check the installation of [node-gyp](https://npmjs.org/package/node-gyp)
