### ISSUE TITLE
Canvasengine and Express together?

### ISSUE THREAD

**Issue by Yutenko** [RSamaium/CanvasEngine#17]
Is it possible to use both?

Since i don't know to pass a port to expressserver, when canvasengine is already listening to it

var express = require('express')
  , http = require('http');

var app = express();
var server = http.createServer(app);
var io = require('socket.io').listen(server);
var CE = require("canvasengine").listen(3000);
server.listen(3000);

So 3000 for instance is already in use.

**Comment by RSamaium** [comment]
Added in 1.3.0. Example :

```
  var express = require('express'),
      app = express(), 
      server = require('http').createServer(app),
      CE = require("canvasengine").listen(server, 8333);

    app.get('/', function (req, res) {
      res.sendfile(__dirname + '/client.html');
    });

    CE.Model.init("Main", ["start"], {

      initialize: function(socket) {

      }

    });
```
