### ISSUE TITLE
Performance on mobile

### ISSUE THREAD

**Issue by Yutenko** [RSamaium/CanvasEngine#19]
Is there no optimization in the rendering, that we have to use CocoonJS?
It seems your engine redraws the whole picture when scrolling or moving with an Element. 

Or is there another "trick" do get above 5 fps on mobile. 
I'am using Tiled and loading the JSON from Node.js to the client.

Thanks in advance

**Comment by RSamaium** [comment]
Hello,

Yes, I am trying to improve performance but rather complex on mobile (performance is greatly reduced)

But can you specify : 

> It seems your engine redraws the whole picture when scrolling or moving with an Element.

Because it must redraw elements :)

> Or is there another "trick" do get above 5 fps on mobile.

Do you have a code to show ?

**Comment by Yutenko** [comment]
Hello

thanks for the fast answer.

```
     var tiled = world.canvas.Tiled.new();
          tiled.ready(function() {         
       // draw Player and Clients
            for(var i = 0; i < world.clients.length; i++) drawCharacter(world.clients[i]); 
           drawCharacter(world.c); 

           stage.append(world.map);
    });
    tiled.load(this, world.map, world.mapJSONpath);
```

//////////////Draw-Character///////////////

```
    function drawCharacter(ch, stage){
    var spritesheet = world.canvas.Spritesheet.new('charset' + ch.charsetKey , {
     grid: [{
        size: ch.spritesheet.matrixSize,
       tile: ch.spritesheet.tileSize,
      set:  ch.spritesheet.matrix,
      reg: [-ch.x, -ch.y]
     }]
  });

  var client = world.scene.createElement();
  client.x = ch.x;
  client.y = ch.y;
  ch.element = client;
  spritesheet.draw(client, ch.characterSetId+1);
  ch.spritesheet.ceSpritesheet = spritesheet;

  world.map.append(client);
```

}

This is called in the ready() function of the Scene. My object world saves all of its elements.

You can test it here. Its a simple map, 2 layers and 2 tilesets. One Spritesheet that scrolls the map.
http://destrudo.de:3000/
On mobile this is getting not above 3-5 fps.

**Comment by RSamaium** [comment]
Try using the [pack()](http://canvasengine.net/doc/?p=core.element.manipulate.pack) method on the map element.

**Comment by Yutenko** [comment]
Jumped from ~21 to ~59 fps, which was the first result i expected on "plain grass 2 layered".

Thanks for the tip. I only have to fix some code to get it working again (don't know what causes the issue, but i'll fix it).

Many thanks - closed.
