### ISSUE TITLE
Tiled importer for rectangular textures

### ISSUE THREAD

**Issue by juliendeville** [RSamaium/CanvasEngine#2]
Tiled.js line 58:

self.tile_w = data.tileheight;
self.tile_h = data.tilewidth;

  I
 V

self.tile_h = data.tileheight;
self.tile_w = data.tilewidth;

**Comment by RSamaium** [comment]
Hello,

Ok, It's fixed in v1.0.7 (https://github.com/RSamaium/CanvasEngine/commit/a57d68dc3031c292c1efda464f2cb64d8a2d275a#L10L58)
