### ISSUE TITLE
Click event doesn't work after changing Element's Position.

### ISSUE THREAD

**Issue by Xulai** [RSamaium/CanvasEngine#20]
I have moving elements that I wish for the user to be able to click and get a menu from which follows the elements having it's own buttons however whenever I change the position of an element I am unable to get the click event working. It is fine if I comment out the position change. (Using A custom Class which contains an Entity using entity.position(newposx,newposy) to change on version 1.2.7)
Bug? / Am I doing something wrong?

**Comment by RSamaium** [comment]
Hello,

No problem on my side :

http://jsfiddle.net/WebCreative5/6pzwp

What is your code ?

**Comment by Xulai** [comment]
Hi, thanks for responding so quickly :)
http://jsfiddle.net/967RJ/ 
Here's an example as simple as I could make it.

**Comment by RSamaium** [comment]
`this` refers to the element in the click function and not your class `EntityContainer`. It is therefore access to your class

```
var self = this;

entity.el.on("click", function(e) {

       if (self.getColor("red"))
           self.changeColor("green");
       else
           self.changeColor("red");

 });
```

http://jsfiddle.net/WebCreative5/967RJ/1/

**Comment by Xulai** [comment]
Oh I didn't notice that. But it doesn't apply to my original code as I do use var self = this; when needed.. I'm not sure what I've done wrong. 
Here's the pastebin with the associated classes I use. 
http://pastebin.com/WKKSX453

**Comment by Xulai** [comment]
http://jsfiddle.net/ALPet/

Here's the example before but with the square now being an image. The click event function doesn't get called.

**Comment by RSamaium** [comment]
CanvasEngine uses `getImageData()` of  the HTML5 Canvas whether the user clicks on the image.  However, the code loads an image on an external server, which poses a security problem in the browser : 

```
 Unable to get image data from canvas because the canvas has been tainted by cross-origin data.
```

Google Chrome 29.0

The solution is to use images with **relative paths**

**Comment by Xulai** [comment]
I do however use images with relative paths in my original code and I get the same result. 
http://jsfiddle.net/BP5W3/
Jsfiddle with relative image.. The opacity code doesn't work, but making it output to console worked.. I guess I'll just rewrite the original code. I have no idea what's gone wrong in the original.

**Comment by RSamaium** [comment]
The problem is that you put the code in the rendering method :

```
 stage.append(entity.el);
```

This means that you add to **each render**,which reduces the performances of the render and adds several elements one over the other. So, it is the opacity of an element is changed but not visible because another element with `opacity=1` is added just after.

It is better to add the addition to the `ready` method :

http://jsfiddle.net/WebCreative5/BP5W3/1

> I added the comment `Changed`

**Comment by Xulai** [comment]
Oh.. I am an idiot.. more used to drawing to screen every render than appending just once.
Thanks for your patience with me

**Comment by RSamaium** [comment]
No worries ;)
