### ISSUE TITLE
Slide Transitions

### ISSUE THREAD

**Issue by marcilioleite** [RSamaium/CanvasEngine#23]
I want make transitions as slideLeft, slideTop... Is that possible in CE? I've found only image and fade transitions.

**Comment by RSamaium** [comment]
No.

But, you can use Tween effect :

http://canvasengine.net/doc/?p=extends.timeline

**Comment by marcilioleite** [comment]
Thanks, but using Tween, I can't move two Scenes simultaneously. My intention is make transitions like Angry birds Star Wars, inspired by the movie... But, if is not possible, ok. Thank you. =)
