### ISSUE TITLE
Tiled.js gives undefined tileset variable on line 182

### ISSUE THREAD

**Issue by azerkail** [RSamaium/CanvasEngine#26]
So I'm trying this framework out for the first and I had an immense struggle trying to get here to where I am (after finding out RPG JS doesn't support map imports form Tiled Map Editor had to switch back and do it on CE), I finally got the point where I'm trying to import maps from the Tiled Map Editor. After taking the smaller tutorial from the Tiled Map Editor site I made my map on JSON and tried to import it using the example available on the Canvas Engine website called "Sprite on Tilemap" - I removed all the code relative to the scrolling and only used the code which allows me to import the map, after solving some issues (with the name of the images) I got stuck on a dead end that I can't fix. 
Firefox gives me the following error when I use the latest Tiled.js extension:
TypeError: tileset is undefined @ http://localhost/CanvasEngine/js/extends/Tiled.js:182

I have no idea what's the problem here since I didn't develop the extension, curious fact though when I use the Tiled.js extension from the example "Sprite on Tilemap" the map is drawn on the screen and it works. (because it is an older version I believe)

**Comment by RSamaium** [comment]
Hello,

I made a correction to the Tiled.js file. You can try on your side if it works ?

**Comment by azerkail** [comment]
Hey!

Thanks for the quick response, yes the problem is fixed the map is finally displayed with no problems at all.

I have a question if you have time to answer, can I use both Canvas Engine and RPG JS simultaneously? I want to use RPG JS to manage events and such but I also want to use most of the Canvas Engine abilities such as loading maps, managing objects and the player etc etc etc... is this possible?

Thank you for your time and have a nice day!

**Comment by RSamaium** [comment]
Yes, you can use plenty CanvasEngine
1. To create a scene :
   
   ```
   RPGJS.Scene.New({
       name: "My_Scene"
       ready: function(stage) {
   
       }
   });
   ```
   
   it works as scenes CanvasEngine. A call with the same [parameters as CanvasEngine](http://canvasengine.net/doc/?p=core.scene.call) : 
   
   ```
   RPGJS.scene.call("My_Scene");
   ```
2. Get the scene of the map or the sprites on the map :
   
   ```
   var scene = RPGJS_Canvas.Scene.get("Scene_Map");
   var spriteset = scene.getSpriteset(); 
   var chara = spriteset.getEvent(0);  // 0 is player
   
   chara.getSprite(); // CanvasEngine Element
   ```
   
   There is an example of the [RPGJS website](rpgjs.com)
3. To use classes CanvasEngine. Variable : 
   
   ```
    RPGJS_Canvas
   ```
   
   Example : 
   
   ```
    RPGJS_Canvas.Input.press(Input.Enter, function() {
   
    });
   ```

Get Started : http://rpgjs.com/v2/doc/?p=tuto-get_started.html
