### ISSUE TITLE
when i go out on bottom of canvas , the scroll stop folow me when i remove on the screen ?

### ISSUE THREAD

**Issue by zimzim62000** [RSamaium/CanvasEngine#27]
Hello,
I noticed a strange thing about the element of scrolling.

When I scroll out of the top, right, or left no worries it realigns perfectly.

By cons when my element go out of bottom canvas  the scroll dont move when i go up or left ?

i have a test on ligne for you if you can see why ?
move the caractere on left right top canvas and enter on canvas the scroll folow you .

but when you do this on bottom he stop :/

http://dragons.webcv.fr

Thx for your times guys .

**Comment by RSamaium** [comment]
Hello,

Indeed, I look at this problem.

**Comment by zimzim62000** [comment]
OK thx. 
i'l try to understand too.

have a nice day
