### ISSUE TITLE
Pause the game

### ISSUE THREAD

**Issue by maxailloud** [RSamaium/CanvasEngine#3]
Currently is there a way to pause the game?

If not have you planned to do it?

**Comment by RSamaium** [comment]
Hello,

I added the pause feature in v1.0.7.
- Methods : `pause` or `togglePause` => Puts the scene paused
- Example : 
  
  ```
  canvas.Scene.new({
     name: "MyScene",
     ready: function(stage) {
         this.pause(true); // return this Scene Class
         console.log(this.pause()); // return true
    },
  });
  ```

Outside the scene

```
 canvas.Scene.get("MyScene").pause(true);
```

[More information](http://canvasengine.net/doc/?p=core.scene.pause)

**Comment by maxailloud** [comment]
Nice thanks.
