### ISSUE TITLE
Input.keyUp

### ISSUE THREAD

**Issue by juliendeville** [RSamaium/CanvasEngine#4]
the function doesn't allow an array of input :

this works
canvas.Input.keyDown(Input.Bottom, function(e) {} 
canvas.Input.keyDown([Input.Bottom, Input.A], function(e) {} 
canvas.Input.keyUp(Input.Bottom, function(e) {} 
canvas.Input.keyUp(Input.A, function(e) {} 

this doesn't works
canvas.Input.keyUp([Input.Bottom, Input.S], function(e) {} 

Input.E should be 69 instead of actual 101, no ?

thanks

**Comment by RSamaium** [comment]
Ok, I look for the array parameter

> Input.E should be 69 instead of actual 101, no ?

Yes, indeed
