### ISSUE TITLE
Dealing with Scroll

### ISSUE THREAD

**Issue by maxailloud** [RSamaium/CanvasEngine#5]
I think there is some lake of documentation for the Scrolling element.

How can you launch the scroll?
Moving the main element or making the scrolling element moving?

I ask this because I succeed making the scroll by making my player move, but my player move faster than the scroll and he can go outside of the canvas.

What's missing in the documentation?

**Comment by RSamaium** [comment]
Hi,

Here is an example of scrolling. Srolling speed must be the same as the main element

http://rsamaium.github.com/CanvasEngine/samples/scrolling

**Comment by maxailloud** [comment]
Nice thanks.

I check that when I got time.
