### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by robik** [RSamaium/CanvasEngine#8]
1. Generated documentation is not helpful at all and hard to read. For example compare [this method](https://github.com/RSamaium/CanvasEngine/blob/master/canvasengine.js#L625) to its [documentation](http://canvasengine.net/doc/?p=core.sound.fadeTo). Parameter list generated is different from original.
2. There's no list of available events [here](http://canvasengine.net/doc/?p=core.element.events.on).
3. More examples :)

**Comment by RSamaium** [comment]
Hello,

Indeed, the parameters are forgotten

> More examples :)

Yes, it will come gradually. But I rely on the community to add :) 
https://github.com/RSamaium/CanvasEngine/tree/gh-pages#canvas-engine-examples-and-demos

Thanks for this issues

**Comment by robik** [comment]
Also, are there any equivalents of DOM `mouseup` and `mousedown` for elements?

**Comment by RSamaium** [comment]
Documentation bugs have been fixed and `mouseup` and `mousedown` were added
