### ISSUE TITLE
Dependences missed??

### ISSUE THREAD

**Issue by tsur** [RSamaium/CanvasEngine#9]
Hello, thanks for this nice framework!

There is something I'm missing.... in the repo, I can see the file "canvasengine-1.1.0.all.min.js" and the file "canvasengine.js"...

Now, when I try to run the framework not using the min version, namely, the "canvasengine.js" in order to be able to debug some part, to understand better how it works and/or to implement new feaures, there are dependences which are lost like for example "Class", so looking at the canvasengine-1.1.0.all.min.js, it's evident there are lot of more code... the problem is where to find that code to be able to run the "canvasengine.js" file, it does not seem to be in the repo.....

Thank you so much

**Comment by RSamaium** [comment]
Hello,

Both files :

```
/core/engine-common.js
/canvasengine.js
```

With more features (example) :

```
/core/engine-common.js
/canvasengine.js
/extends/Scrolling.js
```

**Comment by tsur** [comment]
Hehe, yes, an ugly lapse, thank you so much !
